### ISSUE TITLE
[Master]:Polling slows down gradually over time

### ISSUE THREAD

**Issue by keptenkurk** [keptenkurk/BS440#1]
With no scale connected, polling will slow down gradually from 5 seconds to 5 minutes after 8 hours runtime

**Comment by keptenkurk** [comment]
Try https://github.com/peplin/pygatt/pull/43 where gatttool responses are handled in a saparate thread insted of by locking mechanism

**Comment by IlyaSukhanov** [comment]
I'd love to hear your results I only have 1 device type to test with.
