### ISSUE TITLE
Add multiple people entities

### ISSUE THREAD

**Issue by dimaguy** [keptenkurk/BS440#114]
Currently only one person using the scale is supported at a time, but a scale like the BS444 can support up to 8 people and determine automatically who is getting measured. This could translate into multiple entities in MQTT/Home Assistant (and other plugins)

**Comment by DjZU** [comment]
BS440csv and BS440flask (graphic displays from the CSV data served on a local webserver) do support several persons. I don't know for the other plugins though.

**Comment by Boldfor** [comment]
I have the MQTT-plug-in also working with multiple people.

**Comment by dimaguy** [comment]
Ooh I see, I just didn't know because I saw nothing about it in the readme (maybe a point to improve?) I'll be closing this issue now

**Comment by Boldfor** [comment]
> maybe a point to improve?

Good idea. Added a couple of things to the readme and inline documentation as well already.
