### ISSUE TITLE
WHere to find Fat stats in Google Fit?

### ISSUE THREAD

**Issue by keptenkurk** [keptenkurk/BS440#16]
I managed to create a "Weight" graph of data recorded in Google Fit web app. Is the Fat % also visible in the web app (if so: how?) or does this require the android app?

**Comment by managementboy** [comment]
have not seen a way of checking it. Not even google can help :-(

**Comment by keptenkurk** [comment]
;-)  I noticed that you can create any kind of personal datatype in Google Fit. But then it's up to your application to read and display it. So indeed we could feed it all the scale results...
