### ISSUE TITLE
Working on integrating BS440 with home-assistant

### ISSUE THREAD

**Issue by bimbar** [keptenkurk/BS440#51]
Hi,

unfortunately, it doesn't seem as if I can use this project, since home-assistant is python3, and also this here isn't really built as a library.

So this is more of an FYI and a bit of an apology ;) .

https://github.com/bimbar/bluepy_devices

Best Wishes

Markus

**Comment by keptenkurk** [comment]
@bimbar Your project looks like a very nice step forward of which i can learn a lot. Obviously you are a much more experienced Python programmer.
