### ISSUE TITLE
Typo line 75 BS440domoticz.py

### ISSUE THREAD

**Issue by Tristan79** [keptenkurk/BS440#52]
Typo!

https://github.com/keptenkurk/BS440/blob/master/plugins/_BS440domoticz.py#L75

self should not be there....

**Comment by keptenkurk** [comment]
Is that all thats needs to be changed? Didn't test this "plugin" yet, just rewrote it to fit the new structure.
Dit you test it?

**Comment by Tristan79** [comment]
I hope so :-)  This was reported on domoticz forum.
I still have to play with all the new things added, but no time :-)

**Comment by keptenkurk** [comment]
Ok, well the self has been removed in commit 0c578ca70722b3608c221b5f2ddd1aef78f4f682
