### ISSUE TITLE
Option for Log-Rotate

### ISSUE THREAD

**Issue by giovanne123** [keptenkurk/BS440#53]
Maybe an option or enhancement for the possibility to log-rotate would be fine.
When debugging over some time/days it would be fine to create each day a new logfile to prevent high size logfiles.

python -> logging.handlers.RotatingFileHandler

**Comment by DjZU** [comment]
@giovanne123 Please see #17 and #32

**Comment by keptenkurk** [comment]
Logfile is a lot smaller in the latest version. So i guess this shouldn't be a problem anymore.
