### ISSUE TITLE
Remove BS440 prefix in the plugins

### ISSUE THREAD

**Issue by jovandeginste** [keptenkurk/BS440#69]
Should we remove the `BS440` prefix in the plugin names now?

**Comment by keptenkurk** [comment]
Hmmm. Guess we could leave that as is. Plugins are specific to the BS440 script and i wouldn't want to change the name now that new models emerge...

**Comment by jovandeginste** [comment]
Sure, you're the ... boss! :-)

**Comment by keptenkurk** [comment]
Yeah! Finally...
