### ISSUE TITLE
Question: What is necessary to modify your python script to work with a Beurer BF 700?

### ISSUE THREAD

**Issue by linuxlurak** [keptenkurk/BS440#82]
Fully working Javacode can be found here with many protocol details: https://github.com/oliexdev/openScale/blob/dce3e512b099ebd613c23620738e7abb8194d782/android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerSanitas.java

Can you give me a hint what would be neede to modify your script to work with a BF 700?

Thank you so much for any help!

**Comment by keptenkurk** [comment]
@linuxlurak You would need to find out (from the openScale example) how the BF700 is controlled over Bluetooth. A quick look there shows that at least the BF700 operates in a very different way. Why not use their code? It looks very nice.

**Comment by linuxlurak** [comment]
Thanks for your answer! Yes, their code looks very nice. I'm not capable of translating Java to Python... And I don't understand the BF 700's protocol, it seems. But it's a good hint that you told me the BF 700 works very different. So I can safely presume I will not be able to modify your code to work with this scale ;) It's simple lack of knowledge on my side.
