### ISSUE TITLE
Example csv file for the node-red flow?

### ISSUE THREAD

**Issue by nodecentral** [keptenkurk/BS440#83]
Hi

I was looking at your node-red option, would it be possible for you to share the  csv file or just some lines that are created ?

**Comment by keptenkurk** [comment]
Sure! The CSV output is created automatically by enabling the CSV plugin. Data is written to separate files per person (1.csv, 2.csv etc) and looks like:
timestamp, weight, fat, muscle, bones, water, calories, BMI
`1498684848,79.2,18.9,35.8,2.9,63.7,2638,23.9
1498684932,79.2,18.9,35.8,2.9,63.7,2638,23.9
1498755986,78.3,18.5,36.0,2.9,64.0,2619,23.6
1498798474,75.4,17.5,36.5,2.9,64.8,2558,22.8
1499057011,75.4,17.4,36.6,2.9,64.9,2558,22.8
1499143610,76.7,18.0,36.3,2.9,64.4,2585,23.2`

I changed the node-red flows slightly and added a selectable date from which the data is graphed. 
Not yet published though...
